import type { AppData } from '../types/recipe'

export const SEED_DATA: AppData = {
  version: 1,
  recipes: [
    {
      id: 'sample-sourdough-bagels',
      title: 'Sourdough Discard Protein Bagels',
      description: 'Chewy sourdough bagels with 11g protein each, made with Greek yogurt and sourdough discard.',
      category: 'bread',
      prepTimeMin: 30,
      cookTimeMin: 25,
      servings: 8,
      ingredients: [
        { name: 'warm water', quantity: 0.625, unit: 'cup' },
        { name: 'granulated sugar', quantity: 3, unit: 'tbsp' },
        { name: 'active dry yeast', quantity: 1, unit: 'tsp' },
        { name: 'bread flour', quantity: 4, unit: 'cups' },
        { name: 'Greek yoghurt', quantity: 1, unit: 'cup' },
        { name: 'sourdough discard', quantity: 200, unit: 'g' },
        { name: 'kosher salt', quantity: 2, unit: 'tsp' },
        { name: 'egg white', quantity: 1, unit: '—' },
        { name: 'water (egg wash)', quantity: 1, unit: 'tbsp' },
        { name: 'toppings (e.g. everything bagel seasoning)', quantity: null, unit: '—' },
      ],
      steps: [
        'Combine the warm water and 1 tablespoon granulated sugar in the bowl of a stand mixer fitted with a dough hook. Sprinkle the active dry yeast on top and let sit for 5 minutes until foamy and fragrant. If your yeast does not foam, your yeast is dead — start over with fresh yeast.',
        'Add the flour, Greek yogurt, sourdough discard and salt. Mix until combined and a rough dough forms. Transfer to a smooth work surface and knead by hand for 4–5 minutes until smooth and soft. The dough should be sturdy, not sticky. Add more flour or water (1 tablespoon at a time) if needed.',
        'Transfer the dough to a large, greased bowl and cover with plastic wrap. Let rise for 90 minutes, or until doubled in size.',
        'Turn the dough out and divide into 8–10 equal pieces. Roll each piece into a smooth ball, then press your thumb through the centre and stretch to form a bagel. Make the hole larger than you think it should be. Cover with a clean kitchen towel and let rest for 20 minutes.',
        'Preheat oven to 425°F (220°C). Line 2 baking sheets with parchment paper. Bring a pot with 2 quarts of water and 2 tablespoons granulated sugar to a boil.',
        'Boil bagels for 20–30 seconds on each side. They should float — if not, let remaining bagels rest 10 more minutes and retry. Fit 2–3 at a time. Remove with a slotted spoon to the baking sheets.',
        'Whisk egg white with 1 tablespoon water. Brush bagels with egg wash and sprinkle with toppings.',
        'Bake for 18–22 minutes or until golden brown. Let cool fully before slicing.',
      ],
      sourceUrl: 'https://www.thisjess.com/sourdough-discard-protein-bagels/',
      notes:
        "Greek yogurt and sourdough discard must be at room temperature. Make bagel holes bigger than expected — they shrink. If bagels don't float when boiling, they need more rise time. Freezes well in individual bags.",
      createdAt: '2026-03-13T00:00:00+13:00',
      updatedAt: '2026-03-13T00:00:00+13:00',
    },
    {
      id: 'sample-choc-chip-cookies',
      title: 'Classic Chocolate Chip Cookies',
      description: 'Crispy edges, chewy centres — the perfect everyday chocolate chip cookie.',
      category: 'cookies',
      prepTimeMin: 15,
      cookTimeMin: 12,
      servings: 24,
      ingredients: [
        { name: 'butter, softened', quantity: 225, unit: 'g' },
        { name: 'caster sugar', quantity: 100, unit: 'g' },
        { name: 'brown sugar, packed', quantity: 150, unit: 'g' },
        { name: 'eggs', quantity: 2, unit: '—' },
        { name: 'vanilla extract', quantity: 1, unit: 'tsp' },
        { name: 'plain flour', quantity: 280, unit: 'g' },
        { name: 'baking soda', quantity: 1, unit: 'tsp' },
        { name: 'salt', quantity: 0.5, unit: 'tsp' },
        { name: 'chocolate chips', quantity: 300, unit: 'g' },
      ],
      steps: [
        'Preheat oven to 190°C (375°F). Line two baking sheets with parchment paper.',
        'Beat butter and both sugars together until pale and fluffy, about 3 minutes.',
        'Add eggs one at a time, beating well after each. Mix in vanilla.',
        'Whisk together flour, baking soda and salt, then fold into the butter mixture until just combined.',
        'Fold in chocolate chips.',
        'Drop rounded tablespoons of dough onto prepared baking sheets, spacing about 5cm apart.',
        'Bake for 10–12 minutes until edges are golden but centres still look slightly underdone.',
        'Cool on the baking sheet for 5 minutes — they firm up as they cool. Transfer to a wire rack.',
      ],
      sourceUrl: '',
      notes:
        'For chewier cookies, use more brown sugar than white. Chill the dough for 30 minutes before baking for less spread. Take them out when they look underdone — they finish cooking on the hot tray.',
      createdAt: '2026-03-13T00:00:00+13:00',
      updatedAt: '2026-03-13T00:00:00+13:00',
    },
  ],
}
